### ISSUE TITLE
Differences between code and paper?

### ISSUE THREAD

**Issue by calpt** [morningmoni/UniPELT#1]
Hey,
First of all, thanks a lot for your great work and especially for open-sourcing your code!
While studying your implementation in more detail, we believe to have found some discrepancies between the description of your architecture in the paper and the code implementation that we were unsure about and would love to get some clarification on:

1. In Figure 1 of your paper, you show which modules of the Transformer layer are injected with trainable parameters. For LoRA, it is shown that the Query and Key matrices of the attention are adapted. However, from the code, it seems you actually adapt the Query and Value matrices:
https://github.com/morningmoni/UniPELT/blob/53d3c3594c06a96809b636775abd32d658efb842/transformers/models/bert/modeling_bert.py#L224-L236
Do you have any insights on which of the variants worked better in your setup?
2. As you describe in your paper (and show in Figure 1), each trainable submodule is fitted with one gate G, i.e. the LoRA layer has **one** gate that is shared between the parameters adapting the Q and K/V matrices. However, in your code, the attention matrices are adapted by separate instances of the `LoRA_Linear` module, each of which (by default) adds its own gating layer, thus (from our understanding) resulting in **two** gates per LoRA layer:
https://github.com/morningmoni/UniPELT/blob/53d3c3594c06a96809b636775abd32d658efb842/lora_layers.py#L127-L128
As these variants are slightly different in terms of parameter budget, we would be interested to know which variant you used for performing your experiments?

Would be great to get some insights from your side on these points. And again, thanks for sharing your code!

**Comment by morningmoni** [comment]
1. This is a typo of the paper. Please follow the code implementation (same as [LoRA's original implementation](https://github.com/microsoft/LoRA/blob/c18b175ee040ae1254c37e540a244f75a06dc0a0/examples/NLU/src/transformers/models/roberta/modeling_roberta.py#L172)). I don't have any insights on which one works better tho.
2. Please also follow the code for this one.
Thanks for studying the work in detail. I'll update the paper to make it clearer

**Comment by calpt** [comment]
Thanks for your quick response and the clarification
